import { BellRing, CheckCircle2, CloudRain, History, Info, Settings, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { customerAlerts } from "../../data/userData";
import UserPageHeader from "./UserPageHeader";

const filters = ["All", "Unread", "Weather", "Outage", "Maintenance", "Service"];
const icons = { Weather: CloudRain, Outage: TriangleAlert, Maintenance: Settings, Service: BellRing, Restoration: History };
const severityStyles = { Warning: "bg-amber-50 text-amber-700 border-amber-200", Information: "bg-blue-50 text-blue-700 border-blue-200", Success: "bg-emerald-50 text-emerald-700 border-emerald-200" };

function Alerts() {
  const [filter, setFilter] = useState("All");
  const [alerts, setAlerts] = useState(customerAlerts);
  const unreadCount = alerts.filter((alert) => alert.unread).length;
  const visibleAlerts = alerts.filter((alert) => filter === "All" || (filter === "Unread" ? alert.unread : alert.category === filter));
  const markRead = (id) => setAlerts((current) => current.map((alert) => alert.id === id ? { ...alert, unread: false } : alert));
  const markAllRead = () => setAlerts((current) => current.map((alert) => ({ ...alert, unread: false })));
  const important = alerts.filter((alert) => alert.severity === "Warning").length;
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><UserPageHeader title="Alerts & Notifications" description="Stay informed about service updates, outages, weather conditions, and maintenance activity." /><span className="mb-6 inline-flex w-fit items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-sm font-semibold text-blue-700"><BellRing size={16} />{unreadCount} unread</span></div><section className="grid gap-3 sm:grid-cols-3"><Summary icon={BellRing} label="Total Alerts" value={alerts.length} tone="blue" /><Summary icon={CheckCircle2} label="Unread" value={unreadCount} tone="emerald" /><Summary icon={TriangleAlert} label="Important" value={important} tone="amber" /></section><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-semibold transition ${filter === item ? "bg-blue-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{item}</button>)}</div><button onClick={markAllRead} disabled={!unreadCount} className="shrink-0 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:text-slate-400">{unreadCount ? "Mark all as read" : "All caught up"}</button></div></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{visibleAlerts.length ? visibleAlerts.map((alert) => <AlertCard key={alert.id} alert={alert} onRead={markRead} />) : <EmptyState onReset={() => setFilter("All")} />}</section></div>;
}

function Summary({ icon: Icon, label, value, tone }) { const color = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600" }[tone]; return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${color}`}><Icon size={18} /></span><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div>; }
function AlertCard({ alert, onRead }) { const Icon = icons[alert.category] || Info; return <article className={`flex flex-col gap-4 border-b border-slate-100 p-5 last:border-0 sm:flex-row ${alert.unread ? "bg-blue-50/30" : ""}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Icon size={20} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{alert.category}</span><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${severityStyles[alert.severity]}`}>{alert.severity}</span>{alert.unread && <span className="h-2 w-2 rounded-full bg-blue-600" aria-label="Unread" />}</div><h2 className="mt-3 font-bold text-slate-900">{alert.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{alert.description}</p><div className="mt-4 flex flex-col gap-3 text-xs text-slate-400 sm:flex-row sm:items-center"><span>{alert.time}</span><div className="flex flex-wrap gap-2">{alert.unread && <button onClick={() => onRead(alert.id)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 font-semibold text-slate-600 hover:bg-slate-50">Mark as read</button>}<Link to={alert.path} className="rounded-lg bg-slate-900 px-3 py-1.5 font-semibold text-white hover:bg-slate-800">{alert.action}</Link></div></div></div></article>; }
function EmptyState({ onReset }) { return <div className="p-12 text-center"><BellRing className="mx-auto text-slate-300" size={32} /><h2 className="mt-4 font-bold text-slate-800">No alerts found</h2><p className="mt-1 text-sm text-slate-500">You&apos;re all caught up for this category.</p><button onClick={onReset} className="mt-5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">View all alerts</button></div>; }
export default Alerts;
