import { CheckCircle2, LogOut, Pencil, UserRound } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { userProfile } from "../../data/userData";
import { useAuth } from "../../services/auth.jsx";
import UserPageHeader from "./UserPageHeader";
function Profile() { const { logout } = useAuth(); const navigate = useNavigate(); const [editing, setEditing] = useState(false); const [saved, setSaved] = useState(false); const [profile, setProfile] = useState({ name: userProfile.name, email: userProfile.email, phone: userProfile.phone }); const save = (event) => { event.preventDefault(); setSaved(true); setEditing(false); }; return <><UserPageHeader title="My Profile" description="Manage your customer contact information." /><section className="max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-50 text-blue-600"><UserRound size={22} /></span><div><p className="font-bold">{profile.name}</p><p className="text-sm text-slate-500">Customer profile</p></div></div><button onClick={() => { setEditing(!editing); setSaved(false); }} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold"><Pencil size={16} />{editing ? "Cancel" : "Edit Profile"}</button></div>{saved && <p className="mt-5 flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-medium text-emerald-700"><CheckCircle2 size={17} />Profile updated successfully</p>}<form onSubmit={save} className="mt-6 space-y-4"><ProfileField label="Name" value={profile.name} disabled={!editing} onChange={(value) => setProfile({ ...profile, name: value })} /><ProfileField label="Email" value={profile.email} disabled={!editing} onChange={(value) => setProfile({ ...profile, email: value })} /><ProfileField label="Phone" value={profile.phone} disabled={!editing} onChange={(value) => setProfile({ ...profile, phone: value })} /><ProfileField label="Service Location" value={userProfile.serviceLocation} disabled /><ProfileField label="Connection ID" value={userProfile.connectionId} disabled />{editing && <button className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Save Changes</button>}</form><button onClick={() => { logout(); navigate("/login", { replace: true }); }} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-red-600"><LogOut size={17} />Logout</button></section></>; }
function ProfileField({ label, value, disabled, onChange }) { return <label className="block text-sm font-semibold text-slate-700">{label}<input value={value} disabled={disabled} onChange={(event) => onChange?.(event.target.value)} className={`input mt-2 ${disabled ? "bg-slate-50 text-slate-500" : "bg-white"}`} /></label>; }
export default Profile;
