import { AlertTriangle, CheckCircle2, ChevronLeft, ClipboardPenLine, FileText, Lightbulb, MapPin, Send, Wrench } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { issueTypes, reportHistory, userProfile } from "../../data/userData";
import UserPageHeader from "./UserPageHeader";

const typeIcons = { outage: AlertTriangle, voltage: Lightbulb, equipment: Wrench, area: MapPin, other: ClipboardPenLine };
const statusStyle = { Submitted: "bg-blue-50 text-blue-700", "In Progress": "bg-amber-50 text-amber-700", Resolved: "bg-emerald-50 text-emerald-700" };

function ReportIssue() {
  const [step, setStep] = useState(1);
  const [form, setForm] = useState({ type: "", description: "", location: userProfile.serviceLocation, contact: "Phone", details: "" });
  const [errors, setErrors] = useState({});
  const [submitted, setSubmitted] = useState(null);
  const [reports, setReports] = useState(reportHistory);
  const validate = () => { const next = {}; if (!form.type) next.type = "Select an issue type to continue."; if (!form.description.trim()) next.description = "Describe the issue you are experiencing."; if (!form.location.trim()) next.location = "Enter the service location."; setErrors(next); return !Object.keys(next).length; };
  const next = () => { if (step === 1 && !form.type) { setErrors({ type: "Select an issue type to continue." }); return; } if (step === 2 && !validate()) return; setErrors({}); setStep((current) => Math.min(3, current + 1)); };
  const submit = () => { if (!validate()) { setStep(2); return; } const report = { id: `GG-${10482 + reports.length}`, type: form.type, date: "Today", status: "Submitted", location: form.location }; setReports((current) => [report, ...current]); setSubmitted(report); };
  return <div className="space-y-6"><UserPageHeader title="Report an Issue" description="Tell us what is happening with your electricity service. We&apos;ll help you get it resolved." />{submitted ? <Success report={submitted} onReports={() => setSubmitted(null)} /> : <><Steps step={step} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">{step === 1 && <IssueStep form={form} setForm={setForm} error={errors.type} />} {step === 2 && <DetailsStep form={form} setForm={setForm} errors={errors} />} {step === 3 && <ReviewStep form={form} onEdit={() => setStep(2)} />}<div className="mt-7 flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-between">{step > 1 ? <button onClick={() => setStep(step - 1)} className="inline-flex items-center justify-center gap-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700"><ChevronLeft size={17} />Back</button> : <span />}{step < 3 ? <button onClick={next} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Continue</button> : <button onClick={submit} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white"><Send size={17} />Submit Issue</button>}</div></section></>}<Reports reports={reports} /></div>;
}

function Steps({ step }) { return <div className="grid grid-cols-3 gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm">{[[1, "Issue"], [2, "Details"], [3, "Review"]].map(([number, label]) => <div key={number} className="flex items-center gap-2"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${number <= step ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-400"}`}>{number}</span><span className={`text-sm font-semibold ${number <= step ? "text-slate-800" : "text-slate-400"}`}>{label}</span>{number < 3 && <span className="hidden h-px flex-1 bg-slate-200 sm:block" />}</div>)}</div>; }
function IssueStep({ form, setForm, error }) { return <div><h2 className="text-lg font-bold text-slate-900">What type of issue are you experiencing?</h2><p className="mt-1 text-sm text-slate-500">Choose the option that best describes the problem.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{issueTypes.map((type) => { const Icon = typeIcons[type.icon]; const selected = form.type === type.id; return <button key={type.id} onClick={() => { setForm({ ...form, type: type.id }); }} className={`flex gap-3 rounded-xl border p-4 text-left transition ${selected ? "border-blue-500 bg-blue-50 ring-2 ring-blue-100" : "border-slate-200 hover:border-blue-200 hover:bg-slate-50"}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${selected ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}><Icon size={18} /></span><span><span className="block font-semibold text-slate-800">{type.id}</span><span className="mt-1 block text-sm leading-5 text-slate-500">{type.description}</span></span></button>; })}</div>{error && <p className="mt-4 text-sm font-medium text-red-600">{error}</p>}</div>; }
function DetailsStep({ form, setForm, errors }) { const update = (field) => (event) => setForm({ ...form, [field]: event.target.value }); return <div><h2 className="text-lg font-bold text-slate-900">Issue details</h2><p className="mt-1 text-sm text-slate-500">Help us understand the issue so we can assist you.</p><div className="mt-5 space-y-5"><Field label="Description" error={errors.description}><textarea value={form.description} onChange={update("description")} rows="5" placeholder="Describe what you are experiencing, including when it began..." className="input resize-y" /></Field><Field label="Service Location" error={errors.location}><input value={form.location} onChange={update("location")} className="input" /></Field><Field label="Contact Preference"><div className="flex flex-col gap-2 sm:flex-row">{["Phone", "Email", "No callback"].map((option) => <label key={option} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2.5 text-sm font-medium ${form.contact === option ? "border-blue-500 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600"}`}><input type="radio" name="contact" checked={form.contact === option} onChange={() => setForm({ ...form, contact: option })} />{option}</label>)}</div></Field><Field label="Additional details (optional)"><input value={form.details} onChange={update("details")} placeholder="Anything else we should know?" className="input" /></Field></div></div>; }
function ReviewStep({ form, onEdit }) { return <div><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Review your report</h2><p className="mt-1 text-sm text-slate-500">Please check the details before submitting.</p></div><button onClick={onEdit} className="text-sm font-semibold text-blue-600">Edit Details</button></div><dl className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-200 px-4">{[["Issue type", form.type], ["Description", form.description], ["Location", form.location], ["Contact preference", form.contact]].map(([label, value]) => <div key={label} className="py-3"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-700">{value}</dd></div>)}</dl></div>; }
function Field({ label, error, children }) { return <label className="block text-sm font-semibold text-slate-700">{label}<span className="mt-2 block">{children}</span>{error && <span className="mt-1 block text-sm font-medium text-red-600">{error}</span>}</label>; }
function Success({ report, onReports }) { return <section className="rounded-2xl border border-emerald-200 bg-white p-7 text-center shadow-sm sm:p-10"><CheckCircle2 className="mx-auto text-emerald-500" size={44} /><h2 className="mt-5 text-2xl font-bold text-slate-900">Your issue has been reported</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Thank you. Your report has been successfully submitted.</p><div className="mx-auto mt-6 max-w-md divide-y divide-slate-100 rounded-xl bg-slate-50 p-4 text-left text-sm"><Row label="Report ID" value={report.id} /><Row label="Issue Type" value={report.type} /><Row label="Reported Time" value="Today" /><Row label="Location" value={report.location} /><Row label="Status" value="Submitted" /></div><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/user" className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Back to Dashboard</Link><button onClick={onReports} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">View My Reports</button></div></section>; }
function Reports({ reports }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileText className="text-blue-600" size={20} /><div><h2 className="font-bold text-slate-900">My Reports</h2><p className="mt-1 text-sm text-slate-500">Track your submitted electricity service reports.</p></div></div><div className="mt-5 divide-y divide-slate-100">{reports.map((report) => <div key={report.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-slate-800">{report.id}</p><p className="mt-1 text-sm text-slate-500">{report.type} · {report.date}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyle[report.status]}`}>{report.status}</span></div>)}</div></section>; }
function Row({ label, value }) { return <p className="flex justify-between gap-4 py-2"><span className="text-slate-500">{label}</span><strong className="text-right text-slate-800">{value}</strong></p>; }
export default ReportIssue;
