import { Activity, ArrowRight, BellRing, BrainCircuit, CheckCircle2, CloudRain, ShieldCheck, TriangleAlert, Wrench, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { recentServiceActivity, userProfile } from "../../data/userData";

const quickActions = [[Zap, "View My Service", "Service details and connection", "/user/service"], [TriangleAlert, "Check Outages", "Outage updates in your area", "/user/outages"], [BellRing, "View Alerts", "Weather and service notices", "/user/alerts"], [Wrench, "Report an Issue", "Get help with a problem", "/user/report"]];

function UserDashboard() {
  return <div className="space-y-6 pb-4">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-slate-500">{userProfile.serviceLocation}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">Good afternoon, {userProfile.name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Monitor your electricity service and stay informed about outages and alerts.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-sm font-semibold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />Service Operational</span></section>
    <section className="rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><Zap size={25} fill="currentColor" /></span><div><p className="text-sm font-semibold text-slate-500">Your Electricity Service</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-bold text-slate-900"><CheckCircle2 size={22} className="text-emerald-500" /> Operational</h2><p className="mt-2 text-sm text-slate-500">Your electricity service is currently operating normally.</p></div></div><div className="grid grid-cols-2 gap-x-8 gap-y-2 border-t border-slate-100 pt-4 text-sm sm:border-l sm:border-t-0 sm:pl-8 sm:pt-0"><span className="text-slate-400">Location</span><span className="font-semibold text-slate-700">{userProfile.serviceLocation}</span><span className="text-slate-400">Last updated</span><span className="font-semibold text-slate-700">{userProfile.lastUpdated}</span></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatusCard icon={Activity} title="Service Status" value="Operational" text="Your connection is working normally." tone="emerald" /><StatusCard icon={ShieldCheck} title="Area Risk" value="Low" text="Low disruption risk in your area." tone="blue" /><StatusCard icon={CloudRain} title="Weather Risk" value="Moderate" text="Rain and wind are being monitored." tone="amber" /><StatusCard icon={TriangleAlert} title="Active Outage" value="None" text="No outage reported in your area." tone="emerald" /></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-slate-500">Your Area Risk</p><h2 className="mt-1 text-xl font-bold text-slate-900">{userProfile.serviceLocation}</h2><div className="mt-5 flex items-center justify-between"><span className="text-sm text-slate-500">Risk level</span><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">Low</span></div><div className="mt-3 flex gap-1.5"><span className="h-2 flex-1 rounded-full bg-emerald-500" /><span className="h-2 flex-1 rounded-full bg-slate-200" /><span className="h-2 flex-1 rounded-full bg-slate-200" /></div><div className="mt-2 flex justify-between text-xs font-medium text-slate-400"><span>Low</span><span>Medium</span><span>High</span></div><p className="mt-5 text-sm leading-6 text-slate-600">Your area currently has a low risk of electricity service disruption.</p><p className="mt-4 text-sm font-semibold text-slate-700">Why?</p><ul className="mt-2 space-y-2 text-sm text-slate-500"><li>• Current grid conditions are stable</li><li>• Weather conditions are being monitored</li><li>• Recent maintenance activity is complete</li></ul></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><CloudRain className="mt-0.5 text-amber-600" size={22} /><div><p className="font-semibold text-amber-900">Weather Advisory</p><p className="mt-2 text-sm leading-6 text-amber-800">Moderate rainfall and wind are expected in your area. Your electricity service is currently operating normally, but weather conditions may affect local grid service.</p><Link to="/user/alerts" className="mt-5 inline-flex items-center gap-2 rounded-lg border border-amber-300 bg-white px-3 py-2 text-sm font-semibold text-amber-800 hover:bg-amber-100">View Alerts <ArrowRight size={16} /></Link></div></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><CheckCircle2 size={23} /></span><div><h2 className="font-bold text-slate-900">Power Outage Status</h2><p className="mt-1 text-sm text-slate-500"><span className="font-semibold text-emerald-700">No Active Outage.</span> There is currently no reported power outage in {userProfile.serviceLocation}.</p></div></div><Link to="/user/outages" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Check Outages <ArrowRight size={16} /></Link></div></section>
    <section><h2 className="text-lg font-bold text-slate-900">Quick Actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{quickActions.map(([Icon, title, description, path]) => <Link key={path} to={path} className="group rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-blue-200 hover:bg-blue-50"><Icon size={20} className="text-blue-600" /><p className="mt-4 font-semibold text-slate-900">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-blue-600">Open <ArrowRight size={15} className="transition group-hover:translate-x-0.5" /></span></Link>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Recent Service Activity</h2><div className="mt-5 space-y-5">{recentServiceActivity.map(([date, event]) => <div key={date} className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-emerald-500 ring-4 ring-emerald-50" /><div><p className="text-xs font-semibold text-slate-400">{date}</p><p className="mt-1 text-sm text-slate-700">{event}</p></div></div>)}</div></div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-blue-600"><BrainCircuit size={21} /></div><h2 className="mt-5 text-lg font-bold text-slate-900">GridGuard AI Insight</h2><p className="mt-3 text-sm leading-6 text-slate-600">Your electricity service is currently stable. Weather conditions in your area are being monitored for potential service impact.</p><Link to="/user/ai" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-700">Ask GridGuard AI <ArrowRight size={16} /></Link></div></section>
  </div>;
}

function StatusCard({ icon: Icon, title, value, text, tone }) { const styles = { emerald: "bg-emerald-50 text-emerald-600", blue: "bg-blue-50 text-blue-600", amber: "bg-amber-50 text-amber-600" }; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${styles[tone]}`}><Icon size={20} /></span><p className="mt-4 text-sm font-medium text-slate-500">{title}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p><p className="mt-2 text-sm leading-5 text-slate-500">{text}</p></article>; }
export default UserDashboard;
