# Generated by Django 6.1.1 on 2026-09-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('maintenance_priority', models.CharField(default='P4', max_length=10)),
                ('recommended_action', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('estimated_response', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='core.asset')),
            ],
        ),
    ]
